Build SVM model and check accuracy for following datasets:
    a. mushroom.csv
    b. PastHires.csv
    c. IOT sensor.csv

In [3]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

import matplotlib.pyplot as plt
%matplotlib inline

from sklearn.model_selection import train_test_split

import sklearn



df= pd.read_csv('Mushrooms.csv')
df.head()

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
0,p,x,s,n,t,p,f,c,n,k,...,s,w,w,p,w,o,p,k,s,u
1,e,x,s,y,t,a,f,c,b,k,...,s,w,w,p,w,o,p,n,n,g
2,e,b,s,w,t,l,f,c,b,n,...,s,w,w,p,w,o,p,n,n,m
3,p,x,y,w,t,p,f,c,n,n,...,s,w,w,p,w,o,p,k,s,u
4,e,x,s,g,f,n,f,w,b,k,...,s,w,w,p,w,o,e,n,a,g

In [4]:
df.shape

(8124, 23)

In [5]:
df['class'].value_counts()

e    4208
p    3916
Name: class, dtype: int64

In [6]:
df.isnull().sum()

class                       0
cap-shape                   0
cap-surface                 0
cap-color                   0
bruises                     0
odor                        0
gill-attachment             0
gill-spacing                0
gill-size                   0
gill-color                  0
stalk-shape                 0
stalk-root                  0
stalk-surface-above-ring    0
stalk-surface-below-ring    0
stalk-color-above-ring      0
stalk-color-below-ring      0
veil-type                   0
veil-color                  0
ring-number                 0
ring-type                   0
spore-print-color           0
population                  0
habitat                     0
dtype: int64

In [7]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

# encoding all th label to numbers
for col in df.columns:
    df[col] = le.fit_transform( df[col] )
    
df

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
0,1,5,2,4,1,6,1,0,1,4,...,2,7,7,0,2,1,4,2,3,5
1,0,5,2,9,1,0,1,0,0,4,...,2,7,7,0,2,1,4,3,2,1
2,0,0,2,8,1,3,1,0,0,5,...,2,7,7,0,2,1,4,3,2,3
3,1,5,3,8,1,6,1,0,1,5,...,2,7,7,0,2,1,4,2,3,5
4,0,5,2,3,0,5,1,1,0,4,...,2,7,7,0,2,1,0,3,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8119,0,3,2,4,0,5,0,0,0,11,...,2,5,5,0,1,1,4,0,1,2
8120,0,5,2,4,0,5,0,0,0,11,...,2,5,5,0,0,1,4,0,4,2
8121,0,2,2,4,0,5,0,0,0,5,...,2,5,5,0,1,1,4,0,1,2
8122,1,3,3,4,0,8,1,0,1,0,...,1,7,7,0,2,1,0,7,4,2
8123,0,5,2,4,0,5,0,0,0,11,...,2,5,5,0,1,1,4,4,1,2

In [8]:
# Split data in x & y

y=df.iloc[:,0].values
type(y)

numpy.ndarray

In [11]:
x=df.iloc[:,1:23].values
type(x)

numpy.ndarray

In [12]:
from sklearn.svm import SVC
import sklearn
# Build Model
model = SVC()

In [13]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y,random_state=0)

In [14]:
x_train, x_test, y_train, y_test

(array([[2, 3, 9, ..., 1, 5, 1],
        [5, 3, 4, ..., 3, 5, 1],
        [2, 2, 3, ..., 2, 0, 1],
        ...,
        [5, 2, 3, ..., 3, 3, 1],
        [2, 0, 4, ..., 3, 4, 0],
        [5, 3, 3, ..., 3, 5, 0]]), array([[5, 3, 4, ..., 2, 3, 5],
        [2, 3, 3, ..., 2, 5, 0],
        [5, 3, 9, ..., 3, 2, 3],
        ...,
        [5, 3, 2, ..., 7, 4, 0],
        [5, 2, 9, ..., 2, 3, 1],
        [3, 2, 4, ..., 0, 1, 2]]), array([1, 0, 0, ..., 0, 0, 0]), array([1, 0, 0, ..., 1, 0, 0]))

In [15]:
model.fit(x_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [16]:
# Predict using test data 0 y_predicted
y_predicted = model.predict(x_test)
y_expected = y_test

In [17]:

from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_expected, y_predicted)
accuracy

1.0

# So for Mushroom Accuracy is 100%